version: "3.9"
services:
  frontend:
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    image: task-front:latest
    build: ./front
    container_name: task-front
    entrypoint: bash start_front.sh
    hostname: 0.0.0.0
    environment: 
      - PORT=4200
    ports: 
      - "4200:4200"
      - "4205:4205" # documentations
    volumes: 
      - ./front/:/app
  
  node_backend:
      stdin_open: true # docker run -i
      tty: true        # docker run -t
      image: task-back:latest
      build: ./back
      container_name: task-back
      entrypoint: bash start_back.sh
      hostname: 0.0.0.0
      ports: 
        - "3000:3000"
      environment:
        MONGO_URI : mongodb://root:example@mongo:27017
      volumes: 
        - ./back/:/app
      depends_on: 
        - mongo
  
  mongo:
    image: mongo
    container_name: task-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - './db:/data/db'
    ports:
      - 27017:27017
    expose: 
      - 27017


networks: 
  inner_communication:
    driver: bridge



# sudo chown -R $USER:$(id -gn $USER) ./*