#a basic image to start from
FROM node:16

# needed global packages for the project
RUN npm i -g typescript nodemon ts-node expo-cli @expo/ngrok@^4.1.0

# make the binaries of the globaly installed packages avilable in the cli
ENV PATH=/usr/local/bin:/app/node_modules/.bin:$PATH

# defines where to run the 'ENTRYPOINT' command from
WORKDIR /app

# set the default main command of the container to run 'nodemon src/index.ts'
ENTRYPOINT ["/bin/bash" , "-c" ]
CMD ["bash" ]

