version: "3.9"
services:
  angular_frontend:
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    image: angular_one:latest
    build: ./angular_frontend
    container_name: angular_frontend.container
    entrypoint: sh start_angular.sh
    hostname: 0.0.0.0
    ports: 
      - "4200:4200"
    volumes: 
      - ./angular_frontend/:/app
  
  node_backend:
      stdin_open: true # docker run -i
      tty: true        # docker run -t
      image: node_backend:latest
      build: ./node_backend
      container_name: node_backend.container
      entrypoint: sh start_node.sh
      hostname: 0.0.0.0
      ports: 
        - "3000:3000"
      volumes: 
        - ./node_backend/:/app